---
  - name: Get IP Information of EC2 Instance
    ipify_facts:
    register: ip_data

  - name: Output Public IP Address of EC2 Instance
    debug:
      msg: '{{ ip_data.ansible_facts.ipify_public_ip }}'

  - name: Gather Services Information of EC2 Instance
    service_facts:
    register: servives_data

  - name: Output nginx Status
    debug:
      msg: '{{ servives_data.ansible_facts.services["nginx.service"] }}'

  - name: Output todoapp Status
    debug:
      msg: '{{ servives_data.ansible_facts.services["todoapp.service"] }}'