---
  - name: Install nginx
    yum:
      name: nginx
      state: present

  - name: Allow http for firewall
    firewalld:
      zone: public
      service: http
      permanent: yes
      state: enabled
      immediate: yes
      
  - name: Start nginx
    service:
      name: nginx
      enabled: yes
      state: started