---
  - name: Create and Configure VPC
    ec2_vpc_net:
      state: present
      cidr_block: "{{ vpc_cidr }}"
      region: "{{ aws_region }}"
      multi_ok: no
      name: "{{ vpc_prefix }}_VPC"
    register: vpc_data

  - name: Create and Configure Subnet
    ec2_vpc_subnet:
      state: present
      region: "{{ aws_region }}"
      az: "{{ aws_az }}"
      cidr: "{{ vpc_subnet_cidr }}"
      vpc_id: "{{ vpc_data.vpc.id }}"
      tags:
        Name: "{{ vpc_prefix }}_subnet"
    register: subnet_data

  - name: Create and Configure Internet Gateway
    ec2_vpc_igw:
      state: present
      vpc_id: '{{ vpc_data.vpc.id }}'
      region: '{{ aws_region }}'
      tags:
        Name: '{{ vpc_prefix }}_igw'
    register: igw_data


  - name: Create and Configure Routing Table
    ec2_vpc_route_table:
      state: present
      vpc_id: '{{ vpc_data.vpc.id }}'
      region: '{{ aws_region }}'
      tags:
        Name: '{{ vpc_prefix }}_rt'
      subnets:
        - '{{ subnet_data.subnet.id }}'
      routes:
        - dest: 0.0.0.0/0
          gateway_id: '{{ igw_data.gateway_id }}'
    register: route_table_data